import { create } from "zustand";
import { immer } from "zustand/middleware/immer";

const useStore = create(
  immer((set, get) => ({
    language: "",
    currentSound: "",
    currentId: "",
    setCurrentSound: (value: any) => {
      set((state: any) => {
        state.currentSound = value;
      });
    },
    setLoading: (id: number) => {
      set((state: any) => {
        state.main[id - 1].loading = !state.main[id - 1].loading;
      });
    },
    closePrevPause: () => {
      set((state: any) => {
        state.main.forEach((obj: any) => {
          obj.paused = false;
        });
      });
    },
    setPause: (id: number) => {
      set((state: any) => {
        state.main[id - 1].paused = !state.main[id - 1].paused;
      });
    },
    setCurrent: (id: number) => {
      set((state: any) => {
        state.currentId = id;
      });
    },
    main: [
      {
        chapter: 1,
        surah: "Al-Fatihah",
        englishName: "The Opener",
        paused: false,
        loading: false,
      },
      {
        chapter: 2,
        surah: "Al-Baqarah",
        englishName: "The Cow",
        paused: false,
        loading: false,
      },
      {
        chapter: 3,
        surah: "Ali 'Imran",
        englishName: "Family of Imran",
        paused: false,
        loading: false,
      },
      {
        chapter: 4,
        surah: "An-Nisa",
        englishName: "The Women",
        paused: false,
        loading: false,
      },
      {
        chapter: 5,
        surah: "Al-Ma'idah",
        englishName: "The Table Spread",
        paused: false,
        loading: false,
      },
      {
        chapter: 6,
        surah: "Al-An'am",
        englishName: "The Cattle",
        paused: false,
        loading: false,
      },
      {
        chapter: 7,
        surah: "Al-A'raf",
        englishName: "The Heights",
        paused: false,
        loading: false,
      },
      {
        chapter: 8,
        surah: "Al-Anfal",
        englishName: "The Spoils of War",
        paused: false,
        loading: false,
      },
      {
        chapter: 9,
        surah: "At-Tawbah",
        englishName: "The Repentance",
        paused: false,
        loading: false,
      },
      {
        chapter: 10,
        surah: "Yunus",
        englishName: "Jonah",
        paused: false,
        loading: false,
      },
      {
        chapter: 11,
        surah: "Hud",
        englishName: "Hud",
        paused: false,
        loading: false,
      },
      {
        chapter: 12,
        surah: "Yusuf",
        englishName: "Joseph",
        paused: false,
        loading: false,
      },
      {
        chapter: 13,
        surah: "Ar-Ra'd",
        englishName: "The Thunder",
        paused: false,
        loading: false,
      },
      {
        chapter: 14,
        surah: "Ibrahim",
        englishName: "Abraham",
        paused: false,
        loading: false,
      },
      {
        chapter: 15,
        surah: "Al-Hijr",
        englishName: "The Rocky Tract",
        paused: false,
        loading: false,
      },
      {
        chapter: 16,
        surah: "An-Nahl",
        englishName: "The Bee",
        paused: false,
        loading: false,
      },
      {
        chapter: 17,
        surah: "Al-Isra",
        englishName: "The Night Journey",
        paused: false,
        loading: false,
      },
      {
        chapter: 18,
        surah: "Al-Kahf",
        englishName: "The Cave",
        paused: false,
        loading: false,
      },
      {
        chapter: 19,
        surah: "Maryam",
        englishName: "Mary",
        paused: false,
        loading: false,
      },
      {
        chapter: 20,
        surah: "Taha",
        englishName: "Ta-Ha",
        paused: false,
        loading: false,
      },
      {
        chapter: 21,
        surah: "Al-Anbya",
        englishName: "The Prophets",
        paused: false,
        loading: false,
      },
      {
        chapter: 22,
        surah: "Al-Hajj",
        englishName: "The Pilgrimage",
        paused: false,
        loading: false,
      },
      {
        chapter: 23,
        surah: "Al-Mu'minun",
        englishName: "The Believers",
        paused: false,
        loading: false,
      },
      {
        chapter: 24,
        surah: "An-Nur",
        englishName: "The Light",
        paused: false,
        loading: false,
      },
      {
        chapter: 25,
        surah: "Al-Furqan",
        englishName: "The Criterion",
        paused: false,
        loading: false,
      },
      {
        chapter: 26,
        surah: "Ash-Shu'ara",
        englishName: "The Poets",
        paused: false,
        loading: false,
      },
      {
        chapter: 27,
        surah: "An-Naml",
        englishName: "The Ant",
        paused: false,
        loading: false,
      },
      {
        chapter: 28,
        surah: "Al-Qasas",
        englishName: "The Stories",
        paused: false,
        loading: false,
      },
      {
        chapter: 29,
        surah: "Al-'Ankabut",
        englishName: "The Spider",
        paused: false,
        loading: false,
      },
      {
        chapter: 30,
        surah: "Ar-Rum",
        englishName: "The Romans",
        paused: false,
        loading: false,
      },
      {
        chapter: 31,
        surah: "Luqman",
        englishName: "Luqman",
        paused: false,
        loading: false,
      },
      {
        chapter: 32,
        surah: "As-Sajdah",
        englishName: "The Prostration",
        paused: false,
        loading: false,
      },
      {
        chapter: 33,
        surah: "Al-Ahzab",
        englishName: "The Combined Forces",
        paused: false,
        loading: false,
      },
      {
        chapter: 34,
        surah: "Saba",
        englishName: "Sheba",
        paused: false,
        loading: false,
      },
      {
        chapter: 35,
        surah: "Fatir",
        englishName: "Originator",
        paused: false,
        loading: false,
      },
      {
        chapter: 36,
        surah: "Ya-Sin",
        englishName: "Ya Sin",
        paused: false,
        loading: false,
      },
      {
        chapter: 37,
        surah: "As-Saffat",
        englishName: "Those who set the Ranks",
        paused: false,
        loading: false,
      },
      {
        chapter: 38,
        surah: "Sad",
        englishName: 'The Letter "Saad"',
        paused: false,
        loading: false,
      },
      {
        chapter: 39,
        surah: "Az-Zumar",
        englishName: "The Troops",
        paused: false,
        loading: false,
      },
      {
        chapter: 40,
        surah: "Ghafir",
        englishName: "The Forgiver",
        paused: false,
        loading: false,
      },
      {
        chapter: 41,
        surah: "Fussilat",
        englishName: "Explained in Detail",
        paused: false,
        loading: false,
      },
      {
        chapter: 42,
        surah: "Ash-Shuraa",
        englishName: "The Consultation",
        paused: false,
        loading: false,
      },
      {
        chapter: 43,
        surah: "Az-Zukhruf",
        englishName: "The Ornaments of Gold",
        paused: false,
        loading: false,
      },
      {
        chapter: 44,
        surah: "Ad-Dukhan",
        englishName: "The Smoke",
        paused: false,
        loading: false,
      },
      {
        chapter: 45,
        surah: "Al-Jathiyah",
        englishName: "The Crouching",
        paused: false,
        loading: false,
      },
      {
        chapter: 46,
        surah: "Al-Ahqaf",
        englishName: "The Wind-Curved Sandhills",
        paused: false,
        loading: false,
      },
      {
        chapter: 47,
        surah: "Muhammad",
        englishName: "Muhammad",
        paused: false,
        loading: false,
      },
      {
        chapter: 48,
        surah: "Al-Fath",
        englishName: "The Victory",
        paused: false,
        loading: false,
      },
      {
        chapter: 49,
        surah: "Al-Hujurat",
        englishName: "The Rooms",
        paused: false,
        loading: false,
      },
      {
        chapter: 50,
        surah: "Qaf",
        englishName: 'The Letter "Qaf"',
        paused: false,
        loading: false,
      },
      {
        chapter: 51,
        surah: "Adh-Dhariyat",
        englishName: "The Winnowing Winds",
        paused: false,
        loading: false,
      },
      {
        chapter: 52,
        surah: "At-Tur",
        englishName: "The Mount",
        paused: false,
        loading: false,
      },
      {
        chapter: 53,
        surah: "An-Najm",
        englishName: "The Star",
        paused: false,
        loading: false,
      },
      {
        chapter: 54,
        surah: "Al-Qamar",
        englishName: "The Moon",
        paused: false,
        loading: false,
      },
      {
        chapter: 55,
        surah: "Ar-Rahman",
        englishName: "The Beneficent",
        paused: false,
        loading: false,
      },
      {
        chapter: 56,
        surah: "Al-Waqi'ah",
        englishName: "The Inevitable",
        paused: false,
        loading: false,
      },
      {
        chapter: 57,
        surah: "Al-Hadid",
        englishName: "The Iron",
        paused: false,
        loading: false,
      },
      {
        chapter: 58,
        surah: "Al-Mujadila",
        englishName: "The Pleading Woman",
        paused: false,
        loading: false,
      },
      {
        chapter: 59,
        surah: "Al-Hashr",
        englishName: "The Exile",
        paused: false,
        loading: false,
      },
      {
        chapter: 60,
        surah: "Al-Mumtahanah",
        englishName: "She that is to be examined",
        paused: false,
        loading: false,
      },
      {
        chapter: 61,
        surah: "As-Saf",
        englishName: "The Ranks",
        paused: false,
        loading: false,
      },
      {
        chapter: 62,
        surah: "Al-Jumu'ah",
        englishName: "The Congregation, Friday",
        paused: false,
        loading: false,
      },
      {
        chapter: 63,
        surah: "Al-Munafiqun",
        englishName: "The Hypocrites",
        paused: false,
        loading: false,
      },
      {
        chapter: 64,
        surah: "At-Taghabun",
        englishName: "The Mutual Disillusion",
        paused: false,
        loading: false,
      },
      {
        chapter: 65,
        surah: "At-Talaq",
        englishName: "The Divorce",
        paused: false,
        loading: false,
      },
      {
        chapter: 66,
        surah: "At-Tahrim",
        englishName: "The Prohibition",
        paused: false,
        loading: false,
      },
      {
        chapter: 67,
        surah: "Al-Mulk",
        englishName: "The Sovereignty",
        paused: false,
        loading: false,
      },
      {
        chapter: 68,
        surah: "Al-Qalam",
        englishName: "The Pen",
        paused: false,
        loading: false,
      },
      {
        chapter: 69,
        surah: "Al-Haqqah",
        englishName: "The Reality",
        paused: false,
        loading: false,
      },
      {
        chapter: 70,
        surah: "Al-Ma'arij",
        englishName: "The Ascending Stairways",
        paused: false,
        loading: false,
      },
      {
        chapter: 71,
        surah: "Nuh",
        englishName: "Noah",
        paused: false,
        loading: false,
      },
      {
        chapter: 72,
        surah: "Al-Jinn",
        englishName: "The Jinn",
        paused: false,
        loading: false,
      },
      {
        chapter: 73,
        surah: "Al-Muzzammil",
        englishName: "The Enshrouded One",
        paused: false,
        loading: false,
      },
      {
        chapter: 74,
        surah: "Al-Muddaththir",
        englishName: "The Cloaked One",
        paused: false,
        loading: false,
      },
      {
        chapter: 75,
        surah: "Al-Qiyamah",
        englishName: "The Resurrection",
        paused: false,
        loading: false,
      },
      {
        chapter: 76,
        surah: "Al-Insan",
        englishName: "The Man",
        paused: false,
        loading: false,
      },
      {
        chapter: 77,
        surah: "Al-Mursalat",
        englishName: "The Emissaries",
        paused: false,
        loading: false,
      },
      {
        chapter: 78,
        surah: "An-Naba",
        englishName: "The Tidings",
        paused: false,
        loading: false,
      },
      {
        chapter: 79,
        surah: "An-Nazi'at",
        englishName: "Those who drag forth",
        paused: false,
        loading: false,
      },
      {
        chapter: 80,
        surah: "'Abasa",
        englishName: "He Frowned",
        paused: false,
        loading: false,
      },
      {
        chapter: 81,
        surah: "At-Takwir",
        englishName: "The Overthrowing",
        paused: false,
        loading: false,
      },
      {
        chapter: 82,
        surah: "Al-Infitar",
        englishName: "The Cleaving",
        paused: false,
        loading: false,
      },
      {
        chapter: 83,
        surah: "Al-Mutaffifin",
        englishName: "The Defrauding",
        paused: false,
        loading: false,
      },
      {
        chapter: 84,
        surah: "Al-Inshiqaq",
        englishName: "The Sundering",
        paused: false,
        loading: false,
      },
      {
        chapter: 85,
        surah: "Al-Buruj",
        englishName: "The Mansions of the Stars",
        paused: false,
        loading: false,
      },
      {
        chapter: 86,
        surah: "At-Tariq",
        englishName: "The Nightcommer",
        paused: false,
        loading: false,
      },
      {
        chapter: 87,
        surah: "Al-A'la",
        englishName: "The Most High",
        paused: false,
        loading: false,
      },
      {
        chapter: 88,
        surah: "Al-Ghashiyah",
        englishName: "The Overwhelming",
        paused: false,
        loading: false,
      },
      {
        chapter: 89,
        surah: "Al-Fajr",
        englishName: "The Dawn",
        paused: false,
        loading: false,
      },
      {
        chapter: 90,
        surah: "Al-Balad",
        englishName: "The City",
        paused: false,
        loading: false,
      },
      {
        chapter: 91,
        surah: "Ash-Shams",
        englishName: "The Sun",
        paused: false,
        loading: false,
      },
      {
        chapter: 92,
        surah: "Al-Layl",
        englishName: "The Night",
        paused: false,
        loading: false,
      },
      {
        chapter: 93,
        surah: "Ad-Duhaa",
        englishName: "The Morning Hours",
        paused: false,
        loading: false,
      },
      {
        chapter: 94,
        surah: "Ash-Sharh",
        englishName: "The Relief",
        paused: false,
        loading: false,
      },
      {
        chapter: 95,
        surah: "At-Tin",
        englishName: "The Fig",
        paused: false,
        loading: false,
      },
      {
        chapter: 96,
        surah: "Al-'Alaq",
        englishName: "The Clot",
        paused: false,
        loading: false,
      },
      {
        chapter: 97,
        surah: "Al-Qadr",
        englishName: "The Power",
        paused: false,
        loading: false,
      },
      {
        chapter: 98,
        surah: "Al-Bayyinah",
        englishName: "The Clear Proof",
        paused: false,
        loading: false,
      },
      {
        chapter: 99,
        surah: "Az-Zalzalah",
        englishName: "The Earthquake",
        paused: false,
        loading: false,
      },
      {
        chapter: 100,
        surah: "Al-'Adiyat",
        englishName: "The Courser",
        paused: false,
        loading: false,
      },
      {
        chapter: 101,
        surah: "Al-Qari'ah",
        englishName: "The Calamity",
        paused: false,
        loading: false,
      },
      {
        chapter: 102,
        surah: "At-Takathur",
        englishName: "The Rivalry in world increase",
        paused: false,
        loading: false,
      },
      {
        chapter: 103,
        surah: "Al-'Asr",
        englishName: "The Declining Day",
        paused: false,
        loading: false,
      },
      {
        chapter: 104,
        surah: "Al-Humazah",
        englishName: "The Traducer",
        paused: false,
        loading: false,
      },
      {
        chapter: 105,
        surah: "Al-Fil",
        englishName: "The Elephant",
        paused: false,
        loading: false,
      },
      {
        chapter: 106,
        surah: "Quraysh",
        englishName: "Quraysh",
        paused: false,
        loading: false,
      },
      {
        chapter: 107,
        surah: "Al-Ma'un",
        englishName: "The Small kindnesses",
        paused: false,
        loading: false,
      },
      {
        chapter: 108,
        surah: "Al-Kawthar",
        englishName: "The Abundance",
        paused: false,
        loading: false,
      },
      {
        chapter: 109,
        surah: "Al-Kafirun",
        englishName: "The Disbelievers",
        paused: false,
        loading: false,
      },
      {
        chapter: 110,
        surah: "An-Nasr",
        englishName: "The Divine Support",
        paused: false,
        loading: false,
      },
      {
        chapter: 111,
        surah: "Al-Masad",
        englishName: "The Palm Fiber",
        paused: false,
        loading: false,
      },
      {
        chapter: 112,
        surah: "Al-Ikhlas",
        englishName: "The Sincerity",
        paused: false,
        loading: false,
      },
      {
        chapter: 113,
        surah: "Al-Falaq",
        englishName: "The Daybreak",
        paused: false,
        loading: false,
      },
      {
        chapter: 114,
        surah: "An-Nas",
        englishName: "Mankind",
        paused: false,
        loading: false,
      },
    ],
  }))
);

export default useStore;
